# Generated by Django 4.0.6 on 2022-07-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deparment_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_head', to='main_register.employee'),
        ),
    ]
