# Generated by Django 4.0.6 on 2022-07-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_register', '0003_employee_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='deparment_head',
        ),
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_head', to='main_register.employee'),
        ),
    ]
