# Generated by Django 4.0.6 on 2022-07-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_register', '0004_remove_department_deparment_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
